name: CI for project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, Github Actions! My first workflow!"

      - name: Show date
        run: date